name: Scrape M3U8 URL

on:
  push:
    paths:
      - scrape.py

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install ChromeDriver yang cocok
        run: |
          sudo rm /usr/bin/chromedriver || true
          wget -O chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/linux64/chromedriver-linux64.zip
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Run Python Script
        run: python scrape.py
        
      - name: Upload M3U Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: rcti-playlist
          path: rcti.m3u
