name: Scrape M3U8

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run scraper
        run: python scrape.py

      - name: Upload M3U8 to artifact
        uses: actions/upload-artifact@v4
        with:
          name: m3u8-output
          path: output.txt
